DEFAULT_BADGES: dict[str, dict[str, Any]] = {
    BADGE_DISCORD_LINK: {
        "id": 1,
        "name": "DISCORD_BADGE_#001",
        "url": "",
        "description": "Discord account linked to a JTWP player account.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "discord_link"},
    },
    BADGE_VPN_CONNECTION: {
        "id": 2,
        "name": "Vpn_Connection_#002",
        "url": "",
        "description": "Set when a VPN or proxy connection is detected for the player.",
        "automatic": True,
        "flag": True,
        "remove_after_days": 28,
        "criteria": {"type": "vpn_or_proxy"},
    },
    BADGE_TEAMKILLER: {
        "id": 3,
        "name": "TeamKiller_#003",
        "url": "",
        "description": "Set for getting 3 teamkills in a single match.",
        "automatic": False,
        "flag": True,
        "remove_after_days": 7,
        "criteria": {"type": "single_match_teamkills", "threshold": 3},
    },
    BADGE_1000_KILLS: {
        "id": 4,
        "name": "1000_Kills_#004",
        "url": "",
        "description": "Awarded for reaching 1,000 lifetime kills.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "stat_gte", "stat": "kills", "threshold": 1000},
    },
    BADGE_5000_KILLS: {
        "id": 5,
        "name": "5000_Kills_#005",
        "url": "",
        "description": "Awarded for reaching 5,000 lifetime kills.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "stat_gte", "stat": "kills", "threshold": 5000},
    },
    BADGE_10000_KILLS: {
        "id": 6,
        "name": "10000_Kills_#006",
        "url": "",
        "description": "Awarded for reaching 10,000 lifetime kills.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "stat_gte", "stat": "kills", "threshold": 10000},
    },
    BADGE_100_HEADSHOTS: {
        "id": 7,
        "name": "100_Headshots_#007",
        "url": "",
        "description": "Awarded for reaching 100 lifetime headshots.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "stat_gte", "stat": "headshots", "threshold": 100},
    },
    BADGE_1000_HEADSHOTS: {
        "id": 8,
        "name": "1000_Headshots_#008",
        "url": "",
        "description": "Awarded for reaching 1,000 lifetime headshots.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "stat_gte", "stat": "headshots", "threshold": 1000},
    },
    BADGE_100_CONNECTIONS: {
        "id": 9,
        "name": "100_Connections_#009",
        "url": "",
        "description": "Awarded for connecting to JTWP servers 100 times.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "stat_gte", "stat": "times_connected", "threshold": 100},
    },
    BADGE_1000_CONNECTIONS: {
        "id": 10,
        "name": "1000_Connections_#010",
        "url": "",
        "description": "Awarded for connecting to JTWP servers 1,000 times.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "stat_gte", "stat": "times_connected", "threshold": 1000},
    },
    BADGE_VETERAN: {
        "id": 11,
        "name": "Veteran_#011",
        "url": "",
        "description": "Awarded to players first seen at least 365 days ago.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "account_age_days", "threshold": 365},
    },
    BADGE_CLEAN_PLAYER: {
        "id": 12,
        "name": "Clean_Player_#012",
        "url": "",
        "description": "Reserved for future clean-player/reputation criteria.",
        "automatic": False,
        "flag": False,
        "criteria": {"type": "manual"},
    },
    BADGE_STAFF: {
        "id": 13,
        "name": "JTWP_Staff_#013",
        "url": "",
        "description": "Awarded to JTWP staff/admin player profiles.",
        "automatic": True,
        "flag": False,
        "criteria": {"type": "player_admin"},
    },
    BADGE_MANUAL_SPECIAL: {
        "id": 14,
        "name": "Special_Recognition_#014",
        "url": "",
        "description": "Manual badge for special recognition.",
        "automatic": False,
        "flag": False,
        "criteria": {"type": "manual"},
    }, 
    BADGE_015: {
        "id": 15,
        "name": "Negative_K/D_#015",
        "url": "",
        "description": "Set when lifetime deaths exceed lifetime kills.",
        "automatic": True,
        "flag": True,
        "remove_after_days": 14,
        "criteria": {'type': 'negative_kd'},
    },
    BADGE_016: {
        "id": 16,
        "name": "Network_Traveler_#016",
        "url": "",
        "description": "Set when more than 3 unique IP hashes have been recorded.",
        "automatic": True,
        "flag": True,
        "remove_after_days": 0,
        "criteria": {'type': 'ip_hash_count_gt', 'threshold': 3},
    },
    BADGE_017: {
        "id": 17,
        "name": "Bot_Slayer_#017",
        "url": "",
        "description": "Awarded for reaching 1,000 lifetime bot kills.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'stat_gte', 'stat': 'bot_kills', 'threshold': 1000},
    },
    BADGE_018: {
        "id": 18,
        "name": "Alias_Collector_#018",
        "url": "",
        "description": "Set when more than one player name has been recorded.",
        "automatic": True,
        "flag": True,
        "remove_after_days": 0,
        "criteria": {'type': 'name_count_gt', 'threshold': 1},
    },
    BADGE_019: {
        "id": 19,
        "name": "Ban_History_#019",
        "url": "",
        "description": "Set if the player is currently banned or has a recorded JTWP ban history.",
        "automatic": True,
        "flag": True,
        "remove_after_days": 0,
        "criteria": {'type': 'banned_history'},
    },
    BADGE_020: {
        "id": 20,
        "name": "SHACK_Player_#020",
        "url": "",
        "description": "Awarded to players recorded on the SHACK platform.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'platform_is', 'platform': 'SHACK'},
    },
    BADGE_021: {
        "id": 21,
        "name": "PCVR_Player_#021",
        "url": "",
        "description": "Awarded to players recorded on the PCVR platform.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'platform_is', 'platform': 'PCVR'},
    },
    BADGE_022: {
        "id": 22,
        "name": "Server_Hopper_#022",
        "url": "",
        "description": "Awarded after connecting to every currently configured active JTWP server.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'all_active_servers'},
    },
    BADGE_023: {
        "id": 23,
        "name": "Snowball_Fighter_#023",
        "url": "",
        "description": "Awarded for 25 Snowball kills.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'weapon_kills_sum_gte', 'weapons': ['snowball'], 'threshold': 25},
    },
    BADGE_024: {
        "id": 24,
        "name": "Bayonet_Veteran_#024",
        "url": "",
        "description": "Awarded for 100 combined bayonet kills.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'weapon_kills_sum_gte', 'weapons': ['bayonet_held', 'bayonet_charge'], 'threshold': 100},
    },
    BADGE_025: {
        "id": 25,
        "name": "C4_Expert_#025",
        "url": "",
        "description": "Awarded for 100 TTT C4 kills.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'weapon_kills_sum_gte', 'weapons': ['tttc4'], 'threshold': 100},
    },
    BADGE_026: {
        "id": 26,
        "name": "Tank_Commander_#026",
        "url": "",
        "description": "Awarded for 100 combined tank turret and tank MG kills.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'weapon_kills_sum_gte', 'weapons': ['tankturret', 'tankmg'], 'threshold': 100},
    },
    BADGE_027: {
        "id": 27,
        "name": "Road_Warrior_#027",
        "url": "",
        "description": "Awarded for 50 roadkill/runover kills.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'weapon_kills_sum_gte', 'weapons': ['runover'], 'threshold': 50},
    },
    BADGE_028: {
        "id": 28,
        "name": "Knife_Master_#028",
        "url": "",
        "description": "Awarded for 100 combined modern and WW2 knife kills.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'weapon_kills_sum_gte', 'weapons': ['Knife', 'ww2knife'], 'threshold': 100},
    },
    BADGE_029: {
        "id": 29,
        "name": "Flare_Gunner_#029",
        "url": "",
        "description": "Awarded for 50 Flare Gun kills.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'weapon_kills_sum_gte', 'weapons': ['flaregun'], 'threshold': 50},
    },
    BADGE_030: {
        "id": 30,
        "name": "Bot_Exterminator_#030",
        "url": "",
        "description": "Awarded for reaching 5,000 lifetime bot kills.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'stat_gte', 'stat': 'bot_kills', 'threshold': 5000},
    },
    BADGE_031: {
        "id": 31,
        "name": "Headshot_Legend_#031",
        "url": "",
        "description": "Awarded for reaching 5,000 lifetime headshots.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'stat_gte', 'stat': 'headshots', 'threshold': 5000},
    },
    BADGE_032: {
        "id": 32,
        "name": "Century_Club_#032",
        "url": "",
        "description": "Awarded for 100 hours of recorded JTWP playtime.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'total_time_online_gte', 'seconds': 360000},
    },
    BADGE_033: {
        "id": 33,
        "name": "Day_One_Grinder_#033",
        "url": "",
        "description": "Awarded for 24 hours of recorded JTWP playtime.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'total_time_online_gte', 'seconds': 86400},
    },
    BADGE_034: {
        "id": 34,
        "name": "Arsenal_Master_#034",
        "url": "",
        "description": "Awarded for recording at least one kill with 20 different weapons.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'weapon_types_gte', 'threshold': 20, 'minimum_kills_each': 1},
    },
    BADGE_035: {
        "id": 35,
        "name": "Multi-Weapon_Veteran_#035",
        "url": "",
        "description": "Awarded for 100+ kills with at least 5 different weapons.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'weapon_types_gte', 'threshold': 5, 'minimum_kills_each': 100},
    },
    BADGE_036: {
        "id": 36,
        "name": "Name_Changer_#036",
        "url": "",
        "description": "Set when 5 or more names have been recorded.",
        "automatic": True,
        "flag": True,
        "remove_after_days": 0,
        "criteria": {'type': 'name_count_gte', 'threshold': 5},
    },
    BADGE_037: {
        "id": 37,
        "name": "Ancient_Veteran_#037",
        "url": "",
        "description": "Awarded to players first seen at least 1,000 days ago.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'account_age_days', 'threshold': 1000},
    },
    BADGE_038: {
        "id": 38,
        "name": "10K_Connections_#038",
        "url": "",
        "description": "Awarded for 10,000 recorded JTWP connections.",
        "automatic": True,
        "flag": False,
        "criteria": {'type': 'stat_gte', 'stat': 'times_connected', 'threshold': 10000},
    },

}
